<template>
    <!-- <div> -->
    <v-container fluid >

        <v-card>
            <v-card-title>
            <h1>Bolsas 2018:</h1>
            <v-spacer></v-spacer>
            <v-text-field
                v-model="search"
                append-icon="search"
                label="Search"
                single-line
                hide-details
            ></v-text-field>
            </v-card-title>
            <v-data-table
            :headers="headers"
            :items="desserts"
            :search="search"
            :rows-per-page="25"
            :rows-per-page-items="[25, 50, 100]"
            
            
            >
            <template slot="items" slot-scope="props">
                <td>{{ props.item.name }}</td>
                <td class="text-xs-right">{{ props.item.ingeniero }}</td>
                <td class="text-xs-right">{{ props.item.localidad }}</td>
                <td class="text-xs-right">{{ props.item.distib }}</td>
                <td class="text-xs-right">{{ props.item.remito }}</td>
                <td class="text-xs-right">{{ props.item.bellaco }}</td>
                <td class="text-xs-right">{{ props.item.destello }}</td>
                <td class="text-xs-right">{{ props.item.sy120 }}</td>
                <td class="text-xs-right">{{ props.item.sy200 }}</td>
                <td class="text-xs-right">{{ props.item.sy211 }}</td>
                <td class="text-xs-right">{{ props.item.meteoro }}</td>
                <td class="text-xs-right">{{ props.item.sy300 }}</td>
                <td class="text-xs-right">{{ props.item.saeta }}</td>
                <td class="text-xs-right">{{ props.item.sy330 }}</td>
                <td class="text-xs-right">{{ props.item.camba }}</td>
                <td class="text-xs-right">{{ props.item.claraz }}</td>
                <td class="text-xs-right">{{ props.item.zafiro }}</td>
                <td class="text-xs-right">{{ props.item.esmeralda }}</td>
                <td class="text-xs-right">{{ props.item.total }}</td>
                <td class="text-xs-right">{{ props.item.obelix }}</td>
                <td class="text-xs-right">{{ props.item.odisseo }}</td>
                <td class="text-xs-right">{{ props.item.varios }}</td>
            </template>
            <v-alert slot="no-results" :value="true" color="error" icon="warning">
                Your search for "{{ search }}" found no results.
            </v-alert>
            </v-data-table>
        </v-card>

    </v-container>
    <!-- </div> -->
</template>

<script>
export default {


  data: () => {
      return {
        search: '',
        headers: [
          {
            text: 'RAZON SOCIAL',
            align: 'left',
            sortable: true,
            value: 'name',
            width: '1%'
          },
          { text: 'INGENIERO', value: 'ingeniero', align: 'right', width: '1%' },
          { text: 'LOCALIDAD', value: 'localidad', align: 'right', width: '1%' },
          { text: 'DISTIB', value: 'distib', align: 'right', width: '1%' },
          { text: 'REMITO', value: 'remito', align: 'right', width: '1%' },
          { text: 'BUCK BELLACO', value: 'bellaco', align: 'right', width: '1%' },
          { text: 'BUCK DESTELLO', value: 'destello', align: 'right', width: '1%' },
          { text: 'SY 120', value: 'sy120', align: 'right', width: '1%' },
          { text: 'SY 200', value: 'sy200', align: 'right' },
          { text: 'SY 211', value: 'sy211', align: 'right' },
          { text: 'BUCK METEORO', value: 'meteoro', align: 'right' },
          { text: 'SY 300', value: 'sy300', align: 'right' },
          { text: 'BUCK SAETA', value: 'saeta', align: 'right' },
          { text: 'SY 330', value: 'sy330', align: 'right' },
          { text: 'BUCK CAMBA', value: 'camba', align: 'right' },
          { text: 'BUCK CLARAZ', value: 'claraz', align: 'right' },
          { text: 'BUCK ZAFIRO', value: 'zafiro', align: 'right' },
          { text: 'BUCK ESMERALDA', value: 'esmeralda', align: 'right' },
          { text: 'TOTAL', value: 'total', align: 'right' },
          { text: 'OBELIX', value: 'obelix', align: 'right' },
          { text: 'ODISSEO', value: 'odisseo', align: 'right' },
          { text: 'VARIOS', value: 'varios', align: 'right' },
        ],
        desserts: [
            {
                "value": "false",
                "name": "JORGE LATERZA",
                "ingeniero": "",
                "localidad": "NECOCHEA",
                "distib": "5",
                "remito": "",
                "bellaco": "",
                "destello": "",
                "sy120": "",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "",
                "sy330": "",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "0",
                "obelix": "",
                "odiseo": "",
                "varios": " "
            },
            {
                "value": "false",
                "name": "ALONSO DAMIAN",
                "ingeniero": "PREMIO DIA CAMPO",
                "localidad": "TRES ARROYOS",
                "distib": "6",
                "remito": "11098",
                "bellaco": "",
                "destello": "",
                "sy120": "10",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "",
                "sy330": "",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "10",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "EL TALERO",
                "ingeniero": "ING. ETCHEVERRY",
                "localidad": "LAPRIDA",
                "distib": "6",
                "remito": "11381",
                "bellaco": "",
                "destello": "1",
                "sy120": "1",
                "sy200": "",
                "sy211": "1",
                "meteoro": "",
                "sy300": "",
                "saeta": "",
                "sy330": "",
                "camba": "1",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "4",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "PUESTOLOB",
                "ingeniero": "NECOCHEA",
                "localidad": "NECOCHEA",
                "distib": "6",
                "remito": "11046",
                "bellaco": "",
                "destello": "",
                "sy120": "",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "",
                "sy330": "",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "0",
                "obelix": "",
                "odiseo": "",
                "varios": "15 AIKEN - PREMIO DIA DE CAMPO"
            },
            {
                "value": "false",
                "name": "GONZALEZ MONTANER",
                "ingeniero": "ING. DINAPOLI",
                "localidad": "TS.AS./AZUL",
                "distib": "6",
                "remito": "11253/11300",
                "bellaco": "10",
                "destello": "12",
                "sy120": "10",
                "sy200": "12",
                "sy211": "12",
                "meteoro": "12",
                "sy300": "",
                "saeta": "10",
                "sy330": "10",
                "camba": "10",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "98",
                "obelix": "",
                "odiseo": "",
                "varios": "1 BLS DEL NUEVO IMI"
            },
            {
                "value": "false",
                "name": "GONZALEZ MONTANER",
                "ingeniero": "GASTON COLLOVA",
                "localidad": "NEC/TAND/AZUL",
                "distib": "6",
                "remito": "11355",
                "bellaco": "",
                "destello": "",
                "sy120": "",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "",
                "sy330": "12",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "12",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "AACREA",
                "ingeniero": "ZAPICO",
                "localidad": "NECOCHEA",
                "distib": "6",
                "remito": "11430",
                "bellaco": "2",
                "destello": " ",
                "sy120": "2",
                "sy200": " ",
                "sy211": " ",
                "meteoro": " ",
                "sy300": "",
                "saeta": "2",
                "sy330": "",
                "camba": " ",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "6",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "ALEA Y CIA SA",
                "ingeniero": " ",
                "localidad": "NECOCHEA",
                "distib": "6",
                "remito": "11234",
                "bellaco": "",
                "destello": "1",
                "sy120": "",
                "sy200": "",
                "sy211": "",
                "meteoro": "1",
                "sy300": "",
                "saeta": "1",
                "sy330": "",
                "camba": "",
                "claraz": "1",
                "zafiro": "",
                "esmeralda": "",
                "total ": "4",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "AGRON. OLAVARRIA",
                "ingeniero": "ALBANO MARCOS",
                "localidad": "OLAVARRIA",
                "distib": "6",
                "remito": "11403/11477",
                "bellaco": "",
                "destello": "1",
                "sy120": "1",
                "sy200": "",
                "sy211": "1",
                "meteoro": "",
                "sy300": "",
                "saeta": "31",
                "sy330": "",
                "camba": "1",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "35",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "BASF ARG.",
                "ingeniero": "PABLO ANGELETTI",
                "localidad": "TANDIL",
                "distib": "6",
                "remito": "11418",
                "bellaco": "",
                "destello": "",
                "sy120": "",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "",
                "sy330": "7",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "7",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "ESC.AGROP.LOBERIA",
                "ingeniero": "",
                "localidad": "LOBERIA",
                "distib": "6",
                "remito": "11427/11557",
                "bellaco": "",
                "destello": "",
                "sy120": "",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "",
                "sy330": "30",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "30",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "REG.AAPRESID AZUL/TANDIL",
                "ingeniero": "ING. EUGENIA R.PUCH",
                "localidad": "TANDIL",
                "distib": "6",
                "remito": "",
                "bellaco": "",
                "destello": "",
                "sy120": "",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "",
                "sy330": "",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "0",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "COOP.AGRARIA TS.AS.",
                "ingeniero": "",
                "localidad": "TRES ARROYOS",
                "distib": "6",
                "remito": "11608",
                "bellaco": "",
                "destello": "",
                "sy120": "1",
                "sy200": "",
                "sy211": "1",
                "meteoro": "",
                "sy300": "",
                "saeta": "1",
                "sy330": "",
                "camba": "1",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "4",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "SYNGENTA AGRO SA",
                "ingeniero": "MATIAS FLORES",
                "localidad": "OLAVARRIA",
                "distib": "6",
                "remito": "11599",
                "bellaco": "",
                "destello": "",
                "sy120": "",
                "sy200": " ",
                "sy211": " ",
                "meteoro": "",
                "sy300": "",
                "saeta": "",
                "sy330": "3",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "3",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "SUDESTE DE CREA",
                "ingeniero": "ING. ANDREA ROSSO",
                "localidad": "M.D.PLATA",
                "distib": "6",
                "remito": "11235",
                "bellaco": "1",
                "destello": "1",
                "sy120": "1",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "",
                "sy330": "",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "3",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "INTA LOBERIA",
                "ingeniero": "ING. ERREGUERENA",
                "localidad": "LOBERIA",
                "distib": "6",
                "remito": "11256",
                "bellaco": "",
                "destello": "1",
                "sy120": "1",
                "sy200": "",
                "sy211": "3",
                "meteoro": "",
                "sy300": "",
                "saeta": "",
                "sy330": "",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "5",
                "obelix": "",
                "odiseo": "",
                "varios": "1 BLS. AIKEN Y 1 YAPA SI SE APRUEBA"
            },
            {
                "value": "false",
                "name": "AAPRESID ",
                "ingeniero": "ING. MAGALI GUTIERREZ",
                "localidad": "BAHIA BLANCA",
                "distib": "7",
                "remito": "11530",
                "bellaco": "",
                "destello": "",
                "sy120": "",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "5",
                "sy330": "5",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "10",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "CORFO",
                "ingeniero": "BEISTEGUI JUAN ANDRES",
                "localidad": "P.LURO",
                "distib": "7",
                "remito": "11104",
                "bellaco": "",
                "destello": "3",
                "sy120": "",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "",
                "sy330": "",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "3",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "INTA CHACRA CARHUE",
                "ingeniero": "",
                "localidad": "CARHUE",
                "distib": "7",
                "remito": "11202",
                "bellaco": "",
                "destello": "1",
                "sy120": "1",
                "sy200": " ",
                "sy211": "1",
                "meteoro": "",
                "sy300": "",
                "saeta": "1",
                "sy330": "",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "4",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "CHACRA BARROW",
                "ingeniero": "DIPANE/R.H.PEREZ",
                "localidad": "C.DORREGO",
                "distib": "7",
                "remito": "11529",
                "bellaco": "1",
                "destello": "1",
                "sy120": "",
                "sy200": "",
                "sy211": "1",
                "meteoro": "1",
                "sy300": "",
                "saeta": "",
                "sy330": "",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "ING. CERDA CORINA",
                "ingeniero": "EEA INTA BORDENAVE",
                "localidad": "BORDENAVE",
                "distib": "7",
                "remito": "11145",
                "bellaco": "",
                "destello": "1",
                "sy120": "",
                "sy200": "",
                "sy211": "",
                "meteoro": "1",
                "sy300": "",
                "saeta": "",
                "sy330": "",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "2",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "INTA ONCATIVO",
                "ingeniero": "JOSEFINA MOLINO",
                "localidad": "ONCATIVO",
                "distib": "8",
                "remito": "11126",
                "bellaco": "",
                "destello": "2",
                "sy120": "2",
                "sy200": "",
                "sy211": "2",
                "meteoro": "",
                "sy300": "",
                "saeta": "2",
                "sy330": "2",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "10",
                "obelix": "",
                "odiseo": "",
                "varios": "TELEFONO 03572-15527415"
            },
            {
                "value": "false",
                "name": "INTA SAN FRANCISCO",
                "ingeniero": "EDUARDO CORTES",
                "localidad": "SAN FRANCISCO",
                "distib": "8",
                "remito": "",
                "bellaco": "",
                "destello": "",
                "sy120": "",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "",
                "sy330": "",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "0",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "CREA OESTE ARENOSO",
                "ingeniero": " ",
                "localidad": "TRES LOMAS",
                "distib": "8",
                "remito": "11395",
                "bellaco": "",
                "destello": "",
                "sy120": "2",
                "sy200": "",
                "sy211": "2",
                "meteoro": "",
                "sy300": "",
                "saeta": "2",
                "sy330": "",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "6",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "CREA NORTE DE CORDOTA",
                "ingeniero": "EMPRESA GYSSA",
                "localidad": "SINSACATE",
                "distib": "8",
                "remito": "11151",
                "bellaco": "",
                "destello": "4",
                "sy120": "4",
                "sy200": "",
                "sy211": "4",
                "meteoro": "",
                "sy300": "",
                "saeta": "",
                "sy330": "",
                "camba": "4",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "16",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "AAPRESID PARANA",
                "ingeniero": "ING. PENCO RODRIGO",
                "localidad": "PARANA",
                "distib": "8",
                "remito": "",
                "bellaco": "",
                "destello": "",
                "sy120": "",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "",
                "sy330": "",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "0",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "INTA RAFAELA",
                "ingeniero": "ING. LUCIA ROSSETI",
                "localidad": "RAFAELA",
                "distib": "8",
                "remito": "",
                "bellaco": "",
                "destello": "",
                "sy120": "",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "",
                "sy330": "",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "0",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "ACREA REGION CENTRO",
                "ingeniero": "ING ARIEL ANGELI",
                "localidad": "LABOULAYE",
                "distib": "8",
                "remito": "11179",
                "bellaco": "",
                "destello": "8",
                "sy120": "8",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "",
                "sy330": "",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "16",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "INTA OLIVEROS",
                "ingeniero": "ING. CASTELARIN",
                "localidad": "OLIVEROS",
                "distib": "8",
                "remito": "11171",
                "bellaco": "",
                "destello": "6",
                "sy120": "6",
                "sy200": "",
                "sy211": "6",
                "meteoro": "",
                "sy300": "",
                "saeta": "6",
                "sy330": "6",
                "camba": "6",
                "claraz": "",
                "zafiro": "5KILOS",
                "esmeralda": "5KILOS",
                "total ": "36",
                "obelix": "5KILOS",
                "odiseo": "5KILOS",
                "varios": ""
            },
            {
                "value": "false",
                "name": "GRUPO BROCHERO",
                "ingeniero": "ING. ALEJANDRO CADDILE",
                "localidad": "RIO CUARTO",
                "distib": "8",
                "remito": "11184",
                "bellaco": "",
                "destello": "",
                "sy120": "4",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "4",
                "sy330": "4",
                "camba": "1",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "13",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "CREA SUR DE SANTA FE",
                "ingeniero": "ING. PAULA GELSO",
                "localidad": "V.TUERTO",
                "distib": "8",
                "remito": "11181",
                "bellaco": "",
                "destello": "10",
                "sy120": "10",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "",
                "sy330": "10",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "30",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "GRANEROS",
                "ingeniero": "",
                "localidad": "VICTORIA",
                "distib": "8",
                "remito": "11172/11511",
                "bellaco": "",
                "destello": "3",
                "sy120": "3",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "3",
                "sy330": "",
                "camba": "3",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "12",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "CAPELONI DOMINGO",
                "ingeniero": "ING. CAPELONI DOMINGO",
                "localidad": "GUATIMOZIN",
                "distib": "8",
                "remito": "",
                "bellaco": "",
                "destello": "",
                "sy120": "",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "",
                "sy330": "",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "0",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "SEMINARE SRL",
                "ingeniero": "ING. DEMARCHI FRANCISCO",
                "localidad": "RIO CUARTO",
                "distib": "8",
                "remito": "11185",
                "bellaco": "",
                "destello": "",
                "sy120": "16",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "",
                "sy330": "",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "16",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "GASTALDI HNOS",
                "ingeniero": "OMAR DEPETRIS",
                "localidad": "G.DEHEZA",
                "distib": "8",
                "remito": "11252",
                "bellaco": "",
                "destello": "3",
                "sy120": "",
                "sy200": "",
                "sy211": "3",
                "meteoro": "",
                "sy300": "",
                "saeta": "3",
                "sy330": "",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "9",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "ACA",
                "ingeniero": "ING. LISTELLO /lucas",
                "localidad": "JUNIN/PERGAMINO",
                "distib": "8",
                "remito": "11093",
                "bellaco": "6",
                "destello": "",
                "sy120": "",
                "sy200": "5",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "",
                "sy330": "8",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "19",
                "obelix": "",
                "odiseo": "",
                "varios": "llevarlo y dejar en agronegocios"
            },
            {
                "value": "false",
                "name": "INTA S.A.ARECO",
                "ingeniero": "MOUSEGNE",
                "localidad": "S.A.ARECO",
                "distib": "9",
                "remito": "11119",
                "bellaco": "",
                "destello": "1",
                "sy120": "1",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "1",
                "sy330": "1",
                "camba": "1",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "5",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "AFA ROSARIO",
                "ingeniero": "DIEGO BUSCHITTARI",
                "localidad": "CASILDA",
                "distib": "9",
                "remito": "11133",
                "bellaco": "",
                "destello": "14",
                "sy120": "14",
                "sy200": "",
                "sy211": "14",
                "meteoro": "",
                "sy300": "",
                "saeta": "14",
                "sy330": "14",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "70",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "ATR REG.PERGAMINOCOLON",
                "ingeniero": "ING.ZORZA FEDERICO",
                "localidad": "PERGAMINO",
                "distib": "9",
                "remito": "11120",
                "bellaco": "",
                "destello": "3",
                "sy120": "3",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "3",
                "sy330": "",
                "camba": "3",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "12",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "INTA 25 DE MAYO",
                "ingeniero": "ING.ZANETTINI",
                "localidad": "25 DE MAYO",
                "distib": "9",
                "remito": "11219/11389",
                "bellaco": "",
                "destello": "",
                "sy120": "1",
                "sy200": "",
                "sy211": "1",
                "meteoro": "",
                "sy300": "",
                "saeta": "1",
                "sy330": "",
                "camba": "1",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "4",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "SYNGENTA AGRO SA",
                "ingeniero": "ING. MORICONI",
                "localidad": "PERGAMINO",
                "distib": "9",
                "remito": "",
                "bellaco": "",
                "destello": "",
                "sy120": "",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "",
                "sy330": "",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "0",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "ING.AGRON.JUNIN",
                "ingeniero": "ADRIAN COLANERI",
                "localidad": "JUNIN",
                "distib": "9",
                "remito": "11153",
                "bellaco": "",
                "destello": "1",
                "sy120": "1",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "1",
                "sy330": " ",
                "camba": "1",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "4",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "EEA INTA PERGAMINO",
                "ingeniero": "EUGENIA CENA",
                "localidad": "PERGAMINO",
                "distib": "9",
                "remito": "11121",
                "bellaco": "1",
                "destello": "",
                "sy120": "",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "",
                "sy330": "",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "1",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "ANDREOLI SA",
                "ingeniero": " ",
                "localidad": "CHIVILCOY",
                "distib": "9",
                "remito": "11221/11390",
                "bellaco": "",
                "destello": "",
                "sy120": "1",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "1",
                "sy330": "1",
                "camba": "1",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "4",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "LIAG",
                "ingeniero": "MARCELO LUQUE",
                "localidad": "TUCUMAN",
                "distib": "8",
                "remito": "11061",
                "bellaco": "",
                "destello": "",
                "sy120": "1",
                "sy200": "1",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "1",
                "sy330": "1",
                "camba": "",
                "claraz": "1",
                "zafiro": "",
                "esmeralda": "",
                "total ": "5",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "",
                "ingeniero": "GEAR",
                "localidad": "ROJAS",
                "distib": "9",
                "remito": "",
                "bellaco": "",
                "destello": "",
                "sy120": "",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "",
                "sy330": "",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "0",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "PARCELA DEMOST.",
                "ingeniero": "TOMAS HNOS",
                "localidad": "C.CASARES",
                "distib": "9",
                "remito": "",
                "bellaco": "",
                "destello": "",
                "sy120": "",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "",
                "sy330": "",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "0",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "DON MARIO SEMILLAS",
                "ingeniero": "JAVIER CIERI",
                "localidad": "CHACABUCO",
                "distib": "9",
                "remito": "3942",
                "bellaco": "",
                "destello": "",
                "sy120": "1",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "",
                "sy330": "",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "1",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "INTA EEA PERGAMINO",
                "ingeniero": "ING. GUSTAVO FERRARIS",
                "localidad": "PERGAMINO",
                "distib": "9",
                "remito": "11220/11352",
                "bellaco": "",
                "destello": "",
                "sy120": "2",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "",
                "sy330": "1",
                "camba": "1",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "4",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "INTA CHACRA BARROW",
                "ingeniero": "LILIANA WHERANE",
                "localidad": "TRES ARROYOS",
                "distib": "6",
                "remito": "11535",
                "bellaco": "",
                "destello": "",
                "sy120": "",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "",
                "sy330": "",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "0",
                "obelix": "",
                "odiseo": "",
                "varios": "1 BOLSA DE CADA AVENA"
            },
            {
                "value": "false",
                "name": "CAUDA SEMILLAS",
                "ingeniero": " ",
                "localidad": "CHACABUCO",
                "distib": "9",
                "remito": "11397/11513",
                "bellaco": "",
                "destello": "",
                "sy120": "2",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "",
                "sy330": "4",
                "camba": "",
                "claraz": "2",
                "zafiro": "",
                "esmeralda": "",
                "total ": "8",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "CREA NORTE BS.AS.",
                "ingeniero": "ING. ERMACORA",
                "localidad": "JUNIN/CEREAGRO",
                "distib": "9",
                "remito": "11080",
                "bellaco": "",
                "destello": "",
                "sy120": "6",
                "sy200": "",
                "sy211": "",
                "meteoro": "",
                "sy300": "",
                "saeta": "",
                "sy330": "",
                "camba": "",
                "claraz": "",
                "zafiro": "",
                "esmeralda": "",
                "total ": "6",
                "obelix": "",
                "odiseo": "",
                "varios": ""
            },
            {
                "value": "false",
                "name": "Total:",
                "ingeniero": "",
                "localidad": "",
                "distib": "",
                "remito": "",
                "bellaco": "21",
                "destello": "78",
                "sy120": "116",
                "sy200": "18",
                "sy211": "52",
                "meteoro": "15",
                "sy300": "0",
                "saeta": "93",
                "sy330": "119",
                "camba": "35",
                "claraz": "4",
                "zafiro": "0",
                "esmeralda": "0",
                "total ": "551",
                "obelix": "0",
                "odiseo": "0",
                "varios": ""
            }
                      
        ]
      }
    }
}
</script>
